services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cnoi1986Assdn  # URL-encoded username
      - MONGO_INITDB_ROOT_PASSWORD=55Xg804U3SM  # URL-encoded password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  bot:
    build: .
    container_name: bot_container
    depends_on:
      - mongo
    environment:
      - MONGO_URI="mongodb://cnoi1986Assdn:55Xg804U3SM@mongo:27017/"  # URL-encoded Mongo URI
    ports:
      - "5000:5000"
    restart: always

volumes:
  mongo_data:
