services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME="XH0<Vhg(951." 
      - MONGO_INITDB_ROOT_PASSWORD="55Xg(0=4U3SM" 
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  bot:
    build: .
    container_name: bot_container
    depends_on:
      - mongo
    environment:
      - MONGO_URI="mongodb://XH0<Vhg(951.:55Xg(0=4U3SM@mongo:27017/"  
    ports:
      - "5000:5000"
    restart: always

volumes:
  mongo_data:
