# Remove this line: version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  bot:
    build: .
    container_name: bot_container
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    ports:
      - "5000:5000"
    restart: always

volumes:
  mongo_data:
